# Generated by Django 3.2.6 on 2023-04-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionClassification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mm_predict', models.DecimalField(decimal_places=2, max_digits=5)),
                ('av_predict', models.DecimalField(decimal_places=4, max_digits=6)),
                ('hh_predict', models.DecimalField(decimal_places=4, max_digits=6)),
                ('temp_predict', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tons_predict', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='RealClassification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(max_length=4)),
                ('mm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('av', models.DecimalField(decimal_places=4, max_digits=6)),
                ('hh', models.DecimalField(decimal_places=4, max_digits=6)),
                ('ca', models.DecimalField(decimal_places=4, max_digits=6)),
                ('temp', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
