# Generated by Django 3.2.6 on 2023-04-11 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='states.state'),
        ),
    ]
