# Generated by Django 3.2.6 on 2023-04-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='suministryType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
