# Generated by Django 3.2.6 on 2023-04-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
