# Generated by Django 3.2.6 on 2023-04-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0003_alter_state_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='abbreviation',
            field=models.CharField(max_length=6),
        ),
    ]
